spring:
  application:
    name: affablebean-ui
  thymeleaf:
    cache: false
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true


backend:
  url: http://localhost:8090/
server:
  port: 8080
